### ISSUE TITLE
Battery Levels are not displayed

### ISSUE THREAD

**Issue by gopar** [Phundrak/eshell-info-banner.el#19]
See image:
![Screen Shot 2022-01-04 at 10 56 55 AM](https://user-images.githubusercontent.com/1545083/148109816-68214279-40ae-4dac-9906-ed11bf5534d9.png)

Source of problem:
```
(when (file-readable-p "/sys/") (battery))
```
`(file-readable-p "/sys/")` returns `nil` but `(battery)` returns info.
I removed the `when` statement and it works. \o/

Not sure what the reasoning behind that condition is though.

**Comment by Phundrak** [comment]
This is due to `/sys/' not being readable under Android’s Termux.
Attempting to read anything under `/sys/' crashes Emacs. Another check
should be added so the `when' is only effective on Linux devices.

--
Lucien “Phundrak” Cartier-Tilet

<https://phundrak.com> (Français)

<https://phundrak.com/en> (English)

Sent from GNU/Emacs

**Comment by Phundrak** [comment]
Does the branch https://github.com/Phundrak/eshell-info-banner.el/tree/fix/non-linux-battery fix this issue for you?

**Comment by gopar** [comment]
Yup, it works! \o/
